// Code generated by hertz generator.

package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/app/server/registry"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/gogogo1024/cex-hertz-backend/biz/dal"
	"github.com/gogogo1024/cex-hertz-backend/biz/dal/kafka"
	dalpg "github.com/gogogo1024/cex-hertz-backend/biz/dal/pg"
	"github.com/gogogo1024/cex-hertz-backend/biz/handler"
	"github.com/gogogo1024/cex-hertz-backend/biz/service"
	"github.com/gogogo1024/cex-hertz-backend/biz/util"
	"github.com/gogogo1024/cex-hertz-backend/conf"
	"github.com/gogogo1024/cex-hertz-backend/middleware"
	cexserver "github.com/gogogo1024/cex-hertz-backend/server"
	consulapi "github.com/hashicorp/consul/api"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/logger/accesslog"
	"github.com/hertz-contrib/pprof"
	"github.com/hertz-contrib/registry/consul"
	"go.uber.org/zap/zapcore"
	"gopkg.in/natefinch/lumberjack.v2"
)

func main() {
	cfg := conf.GetConf()
	dal.Init()
	defer kafka.CloseAllWriters() // Event Sourcing V2: 关闭Kafka Writers
	// 注意: `kafkadal.InitWriters()` 会预先为配置中的所有 topic 创建并缓存 `kafka.Writer` 实例，
	// 这在生产环境的“预热”阶段有用（可以在部署或服务启动前建立 TCP 连接以减少首次写入延迟），
	// 但在测试环境或当我们希望按需延迟创建 per-topic writer 时不应自动调用。
	// 因此我们不在这里自动调用 InitWriters()。如果需要在生产中预热，请在部署脚本或启动选项中显式调用：
	//
	//    kafkadal.InitWriters()
	//
	// 例如：在容器启动脚本中，先加载配置并调用 InitWriters()，然后再启动主进程。
	consulClient := initConsul(cfg)
	h := initHertzServer(cfg, consulClient)
	wsServer, pm, localAddr, matchEngine := initBusiness(cfg, h)
	defer h.Shutdown(context.Background())
	defer wsServer.Shutdown(context.Background())

	// 启动 Outbox Dispatcher，负责将 outbox 中持久化的事件发送到 Kafka
	outboxRepo := dalpg.NewOutboxRepo(dalpg.GormDB)
	outboxDispatcher := service.NewOutboxDispatcher(outboxRepo, 10, cfg.Recovery.MaxRetries)
	// 使用 500ms 轮询间隔启动（可根据负载调整）
	outboxDispatcher.Start(context.Background(), 500*time.Millisecond)
	defer outboxDispatcher.Stop()

	// Phase 2.5: 启动恢复检测与执行
	if cfg.Recovery.EnableAutoRecovery {
		if err := initRecovery(context.Background(), cfg, matchEngine); err != nil {
			hlog.Warnf("[main] 自动恢复失败，继续启动: %v", err)
		} else {
			hlog.Infof("[main] 自动恢复检测完成")
		}
	}

	startBackgroundTasks(cfg, pm, consulClient, localAddr)
	registerMiddleware(h)
	registerRoutes(h)
	go h.Spin()
	go wsServer.Spin()
	waitForExit()
}
func initConsul(cfg *conf.Config) *consulapi.Client {
	config := consulapi.DefaultConfig()
	config.Address = cfg.Registry.RegistryAddress[0]
	consulClient, err := consulapi.NewClient(config)
	if err != nil {
		log.Fatal(err)
	}
	return consulClient
}

func initHertzServer(cfg *conf.Config, consulClient *consulapi.Client) *server.Hertz {
	r := consul.NewConsulRegister(consulClient)
	addr := cfg.Hertz.Address
	serviceName := cfg.Hertz.Service
	h := server.Default(
		server.WithHostPorts(addr),
		server.WithRegistry(r, &registry.Info{
			ServiceName: serviceName,
			Addr:        utils.NewNetAddr("tcp", addr),
			Weight:      10,
			Tags:        nil,
		}),
		server.WithExitWaitTime(10*time.Second),
	)
	// Event Sourcing V2: Kafka消费者逻辑已由EventPipeline处理，无需显式关闭
	return h
}

func initBusiness(cfg *conf.Config, h *server.Hertz) (*server.Hertz, *service.PartitionManager, string, *service.PartitionAwareMatchEngine) {
	hsPort := cfg.Hertz.WsPort
	if len(hsPort) > 0 && hsPort[0] == ':' {
		hsPort = hsPort[1:]
	}
	// Event Sourcing V2: Kafka已在dal.Init()中自动初始化，恢复逻辑由EventPipeline处理
	consulAddrs := cfg.Registry.RegistryAddress
	matchPort := cfg.MatchEngine.MatchPort
	pm, err := service.NewPartitionManager(consulAddrs)
	if err != nil {
		hlog.Fatalf("初始化 PartitionManager 失败: %v", err)
	}
	if err := pm.LoadFromConsul(); err != nil {
		hlog.Fatalf("加载分区表失败: %v", err)
	}

	// 初始化并注入迁移协调器（OwnershipTransfer 表迁移与 coordinator wiring）
	if err := service.SetupCoordinators(pm, dalpg.GormDB); err != nil {
		hlog.Fatalf("SetupCoordinators failed: %v", err)
	}

	// ⚠️ Docker环境: 获取持久化的节点标识符(幂等性关键)
	// 优先级: NODE_IDENTITY > POD_NAME > HOSTNAME > localIP:port
	nodeIdentity := getNodeIdentity()
	localAddr := nodeIdentity + ":" + strconv.Itoa(matchPort)
	hlog.Infof("[main] Node identity=%s, localAddr=%s (用于幂等分配NodeID)", nodeIdentity, localAddr)

	wsServer := cexserver.NewWebSocketServer(":"+hsPort, pm, localAddr)
	broadcaster := func(symbol string, msg []byte) {
		cexserver.Broadcast(symbol, msg)
	}
	unicast := func(userID string, msg []byte) {
		cexserver.Unicast(userID, msg)
	}
	matchEngine := service.NewPartitionAwareMatchEngine(pm, localAddr, broadcaster, unicast)
	cexserver.InjectEngine(matchEngine)
	// 注入到全局变量，HTTP handler 可通过 service.GlobalMatchEngine 转发下单请求
	service.GlobalMatchEngine = matchEngine
	service.MatchResultPusher = cexserver.PushMatchResult
	return wsServer, pm, localAddr, matchEngine
}

// Phase 2.5: 恢复启动函数（最优化版本：单次数据库查询）
// 优化点：
// 1. 直接调用 ExecuteRecovery()，避免 ShouldRecover() 的重复查询
// 2. ExecuteRecovery() 内部已检查待恢复项，无需提前检测
// 3. 通过结果的 EventsReplayed 判断是否进行了恢复
func initRecovery(ctx context.Context, cfg *conf.Config, matchEngine *service.PartitionAwareMatchEngine) error {
	if matchEngine == nil {
		return fmt.Errorf("matchEngine is nil")
	}

	recoveryExecutor := service.NewRecoveryExecutor(
		matchEngine,
		matchEngine.GetCheckpointManager(),
		matchEngine.GetEventLog(),
	)

	// 创建恢复上下文
	timeout := time.Duration(cfg.Recovery.RecoveryTimeout) * time.Second
	if timeout == 0 {
		timeout = 30 * time.Second // 默认30秒
	}

	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	// 配置恢复选项
	opts := &service.RecoveryOptions{
		Strategy:              service.INCREMENTAL,
		ValidateAfterRecovery: cfg.Recovery.ValidateAfterRecovery,
		MaxRetries:            cfg.Recovery.MaxRetries,
	}

	// 直接执行恢复（只查 1 次数据库）
	// 内部流程：
	//   1. getPendingRecoveryList() 查询数据库获取待恢复项
	//   2. 如果无待恢复项，返回 EventsReplayed=0
	//   3. 如果有待恢复项，并行恢复所有项目
	result, err := recoveryExecutor.ExecuteRecovery(ctx, opts)
	if err != nil {
		hlog.Errorf("[initRecovery] 恢复执行失败: %v", err)
		return err
	}

	if result == nil {
		hlog.Warnf("[initRecovery] 恢复结果为nil")
		return nil
	}

	// 根据恢复结果判断是否进行了恢复
	if result.EventsReplayed == 0 {
		hlog.Infof("[initRecovery] 无待恢复项，继续正常启动")
	} else {
		hlog.Infof("[initRecovery] 恢复完成: 耗时=%v, 恢复项=%d, 事件数=%d, 验证=%v",
			result.RecoveryEnd.Sub(result.RecoveryStart),
			result.ProcessorName, // 实际应该是多个processor，但这里简化显示
			result.EventsReplayed,
			result.IsValid)
	}

	return nil
}

func startBackgroundTasks(cfg *conf.Config, pm *service.PartitionManager, consulClient *consulapi.Client, localAddr string) {
	service.StartKlineCompensateTask(consulClient)
	metrics := &service.MockPartitionMetrics{} // TODO: 替换为真实采集实现
	autoScaler := service.NewPartitionAutoScaler(pm, metrics, time.Minute)
	go autoScaler.Run(context.Background())
}

func waitForExit() {
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
}

func registerMiddleware(h *server.Hertz) {

	hlog.SetLevel(conf.LogLevel())
	hlog.SetOutput(zapcore.AddSync(&lumberjack.Logger{
		Filename:   conf.GetConf().Hertz.LogFileName,
		MaxSize:    conf.GetConf().Hertz.LogMaxSize,
		MaxBackups: conf.GetConf().Hertz.LogMaxBackups,
		MaxAge:     conf.GetConf().Hertz.LogMaxAge,
	}))
	// pprof
	if conf.GetConf().Hertz.EnablePprof {
		pprof.Register(h)
	}

	// gzip
	if conf.GetConf().Hertz.EnableGzip {
		h.Use(gzip.Gzip(gzip.DefaultCompression))
	}

	// access log
	if conf.GetConf().Hertz.EnableAccessLog {
		h.Use(accesslog.New())
	}

	// recovery
	h.Use(recovery.Recovery())

	// cores
	h.Use(cors.Default())
	middleware.Register(h)
}

func registerRoutes(h *server.Hertz) {
	h.GET("/ping", handler.Ping)
	orderGroup := h.Group("/api")
	//orderGroup.Use(middleware.DistributedRouteMiddleware())
	orderGroup.POST("/order", handler.SubmitOrder)
	orderGroup.GET("/order/:id", handler.GetOrder)
	orderGroup.GET("/orders", handler.ListOrders)
	orderGroup.POST("/order/cancel", handler.CancelOrder)
	orderGroup.GET("/balance", handler.GetBalance)
	orderGroup.GET("/positions", handler.GetPositions)
	orderGroup.GET("/depth", handler.GetDepth)
	orderGroup.GET("/trades", handler.GetTrades)
	orderGroup.GET("/ticker", handler.GetTicker)
	orderGroup.GET("/kline", handler.GetKline)
}

// getNodeIdentity 获取持久化的节点标识符(Docker环境关键)
// 确保容器重启后获得相同的标识符，从而复用NodeID
//
// 优先级:
//  1. NODE_IDENTITY 环境变量 (明确指定, 推荐用于Docker)
//  2. POD_NAME 环境变量 (Kubernetes StatefulSet)
//  3. HOSTNAME 环境变量 (通常稳定)
//  4. 本地IP地址 (最后降级, Docker中可能变化)
//
// 使用方式:
//
//	# Kubernetes (deployment/statefulset中):
//	env:
//	- name: POD_NAME
//	  valueFrom:
//	    fieldRef:
//	      fieldPath: metadata.name
//
//	# Docker Compose中:
//	environment:
//	  NODE_IDENTITY: "exchange-worker-1"
func getNodeIdentity() string {
	// 1. 优先使用NODE_IDENTITY (Docker Compose显式设置)
	if nodeID := os.Getenv("NODE_IDENTITY"); nodeID != "" {
		return nodeID
	}

	// 2. 其次使用POD_NAME (Kubernetes StatefulSet)
	if podName := os.Getenv("POD_NAME"); podName != "" {
		return podName
	}

	// 3. 再次使用HOSTNAME (开发环境或Docker默认)
	if hostname, err := os.Hostname(); err == nil && hostname != "" {
		return hostname
	}

	// 4. 最后降级到本地IP:端口 (不推荐用于分布式, 可能重启后变化)
	localIP := util.GetLocalIP()
	hlog.Warnf("[main] NODE_IDENTITY/POD_NAME/HOSTNAME都未设置, 降级使用localIP=%s (⚠️ Docker中可能不稳定)", localIP)
	return localIP
}
